### ISSUE TITLE
Can U help Me - trouble getting started

### ISSUE THREAD

**Issue by didi909** [christabor/flask_jsondash#142]
I am a new dev in flask_jsondash,i build up the dev environment on my laptop(win10-x64,python 3.5.3-x64).
Now, i was stopped at the demo app.py when the endpoint.py and the mongo are all installed and running.
![4](https://user-images.githubusercontent.com/25740515/28904866-6f1ae468-7840-11e7-92ca-77c5650443d7.jpg)
My trouble is after configured a new Dashboard and three charts on the webpage(localhost:8080),the charts cannot display the content in the datasource.

The raw json code is below:
`{
    "created_by": "global",
    "username": "anonymous",
    "layout": "grid",
    "category": "uncategorized",
    "name": "newDash",
    "modules": [
        {
            "type": "plotly-any",
            "refreshInterval": null,
            "refresh": false,
            "width": "col-5",
            "classes": [],
            "name": "Wid1",
            "order": 2,
            "dataSource": "localhost:5004/plotly-dynamic",
            "guid": "853279c2-c291-de23-a14b-4c402da5de86",
            "override": false,
            "family": "PlotlyStandard",
            "height": 400,
            "row": 1
        },
        {
            "type": "datatable",
            "refresh": true,
            "width": "col-12",
            "classes": [],
            "name": "Wid3",
            "order": 1,
            "height": 300,
            "dataSource": "localhost:5004/dtable",
            "guid": "b602aebd-4dce-ba74-0960-92d6c59c6cd0",
            "override": true,
            "family": "DataTable",
            "refreshInterval": "5",
            "row": 1
        },
        {
            "type": "timeline",
            "refreshInterval": null,
            "refresh": false,
            "width": "col-1",
            "classes": [],
            "name": "Wid2",
            "order": 1,
            "dataSource": "localhost:5004/timeline",
            "guid": "61bad618-56b5-b4d0-fc2a-3d0478c71fa4",
            "override": false,
            "family": "Timeline",
            "height": 400,
            "row": 1
        }
    ],
    "id": "bf8a9334-77f4-11e7-9b53-507b9d2c9401",
    "date": "2017-08-03 11:26:53.117025"
}`

**Comment by christabor** [comment]
Looks like your browser is probably not happy with `localhost:5004`as a url, which is not fully qualified (no protocol is specified). Either add `https://` to the beginning, or use `http://127.0.0.1`. Relative urls can be specified, but they must be prefixed with a `/`.

Let me know if that helps!

**Comment by christabor** [comment]
Another thing - The plotly chart needs to have an `override: true` specified, whereas yours does not. I'll look at making this automatically check the box if this is set, or add better docs here.
