### ISSUE TITLE
[question]How to plot timeseries data using C3js

### ISSUE THREAD

**Issue by bholagabbar** [christabor/flask_jsondash#157]
@christabor  I'm looking to plot something like http://c3js.org/samples/axes_x_tick_values.html which modifies the x axes value as well. Currently, for C3, I am only able to get the standard 1, 2, 3, 4 in the x axis and only able to pass y axis data

```
    @app.route('/graph-data')
    def linechart():
        return jsonify({
            "line1": [1, 4, 3, 10, 12, 14, 18, 10],
            "line2": [1, 2, 10, 20, 30, 6, 10, 12, 18, 2],
        })

```

**Comment by christabor** [comment]
You can use the example format, or click "override" and then pass in the full config that you would normally pass c3 (excluding any JavaScript, as it must be json serialize-able).

**Comment by bholagabbar** [comment]
@christabor I need to pass in the data through my API. Can you link me to the 'example format' ? I really need to get this done for a project and I'm pretty clueless as of now. I'll keep looking!

**Comment by bholagabbar** [comment]
@christabor I need to plot something like this https://stackoverflow.com/a/32950521/4258892

```
data: {
    x: 'x',
    xFormat: '%Y-%m-%dT%H:%M:%S.%LZ',
    columns: [
        ['x', ... ],
        ['data1', ... ]
    ]
}
```

and I have tried a lot but there seems to be no way I can get this to pass from `jsonify` directly. What are the configuration changes to be made?

**Comment by bholagabbar** [comment]
@christabor awaiting your reply!

**Comment by christabor** [comment]
I'll take a look today. Is the above example representative of your entire payload configuration?

**Comment by bholagabbar** [comment]
Yes pretty, much this is what I need. I need to plot something very similar
and this exact configuration works when passed into C3js (ofcourse in
proper JSON)

**Comment by christabor** [comment]
I used your example and was able to get it running with no problem. Here's my configuration:

```
{
    "username": "anonymous",
    "category": "uncategorized",
    "layout": "grid",
    "name": "asdsad",
    "modules": [
        {
            "name": "c3ts",
            "family": "C3",
            "refresh": false,
            "height": 600,
            "width": "col-8",
            "classes": [],
            "dataSource": "http://0.0.0.0:5004/c3ts",
            "override": true,
            "refreshInterval": null,
            "guid": "f8f78659-4d63-61e4-e2cc-ffa2640a950f",
            "type": "timeseries",
            "order": 0,
            "row": 1
        }
    ],
    "created_by": "anonymous",
    "date": "2018-03-16 23:13:21.005435",
    "id": "179a0357-29aa-11e8-ac1e-a0999b0aebbf"
}
```


<img width="1194" alt="screen shot 2018-03-16 at 11 14 23 pm" src="https://user-images.githubusercontent.com/410839/37552313-d427900a-296f-11e8-9ac6-028104d814ec.png">

**Comment by christabor** [comment]
Make sure to check "use custom configuration" in the config. See the screenshot.

<img width="491" alt="screen shot 2018-03-16 at 11 15 51 pm" src="https://user-images.githubusercontent.com/410839/37552325-0fd5e002-2970-11e8-8e13-ee8ef7778e26.png">

**Comment by bholagabbar** [comment]
Okay, I'm a little lost. Here's what I do:
1. Create a dashboard, freeform
2. Edit dashboard, create widget, select C3 timeseries and and enter the
url as data source.

When you clicked on use custom configuration, it says it picks up data from
'config.Datasource', where is this file supposed to be in the project
structure? Is this where you entered the configuration?

**Comment by christabor** [comment]
Config.dataSource is the key used in your config that points to the url serving that data you referenced. Everything you chose should be the same, except the custom override option.

**Comment by bholagabbar** [comment]
Strange, I'm definitely missing something stupid. Here are my current endpoints:

```
@cross_origin()
@app.route('/data')
def data():
    data = dict(
        x='x',
        xFormat='%Y%m%d',
        columns=[
            ['x', '20130101', '20130102', '20130103', '20130104', '20130105', '20130106'],
            ['data1', 30, 200, 100, 400, 150, 2],
            ['data2', 130, 340, 200, 500, 250, 350]
        ]
    )
    return jsonify(data)

@cross_origin()
@app.route('/c3ts')
def c3ts():
    data = {
        "username": "anonymous",
        "category": "uncategorized",
        "layout": "grid",
        "name": "asdsad",
        "modules": [
            {
                "name": "c3ts",
                "family": "C3",
                "refresh": False,
                "height": 600,
                "width": "col-8",
                "classes": [],
                "dataSource": "http://0.0.0.0:8000/data",
                "override": True,
                "refreshInterval": None,
                "type": "timeseries",
                "order": 0,
                "row": 1
            }
        ],
        "created_by": "anonymous",
    }
    return jsonify(data)
```

And this is my add widget constructor,

<img width="905" alt="screen shot 2018-03-17 at 11 37 13 pm" src="https://user-images.githubusercontent.com/11693595/37558601-2862d446-2a3c-11e8-8637-1e3db6a4340a.png">


It still doesn't work (graph keeps rendering with the circle)

**Comment by bholagabbar** [comment]
@christabor Ah perfect, I was only missing checking the 'use custom config button'. Thanks a ton for your help. Cheers!

**Comment by christabor** [comment]
Good to hear!
