### ISSUE TITLE
create a data source endpoint with dynamic parameters

### ISSUE THREAD

**Issue by vincentclaes** [christabor/flask_jsondash#168]
is it possible to create a a widget and add some parameters to the endpoint call dynamically? for example i want to add an input field to my dashboard and based on the value given in the inputfield all my endpoints get updated.

i can hack this by updating the endpoint call in the mongo object, but i was wondering if there was a more clean way to achieve this.

thanks.

**Comment by christabor** [comment]
Yes, this is fully supported if I understand your need correctly. 

See https://github.com/christabor/flask_jsondash/blob/master/README.md#json-configurations-intro and the custom input options. You can easily customize the chart config to generate forms for each widget that will then be called as query parameters.
