### ISSUE TITLE
support for postgresql

### ISSUE THREAD

**Issue by threemonks** [christabor/flask_jsondash#199]
I am trying to use flask_jsondash with my existing flask app, which uses Postgresql database. Any plan on adding support to Postgresql?

**Comment by christabor** [comment]
Definitely considered it at one point,  and designed the orm abstraction with this in mind.  However,  nothing has been done in earnest. I don't think it would be that big an undertaking though.

**Comment by christabor** [comment]
For example, see the [mongo adapter](https://github.com/christabor/flask_jsondash/blob/master/flask_jsondash/mongo_adapter.py). I think something along these lines would work. There is likely too much knowledge of filtering and retrieving of data in the callers of these methods (seen via the `**kwargs` in the above class),  so it might not 100% cut-and-dry. But, I still don't think it would be too hard to support.

**Comment by christabor** [comment]
Would using the json field in postgres serve your needs? That way,  it's a single field and maintains the scheme with zero need for normalizing tables.

**Comment by threemonks** [comment]
Thanks for the suggestion. I dropped the idea at that point, but later on tried dash and decided to embed dash into my existing flask app, kind of hack, but it works for my purpose.
