### ISSUE TITLE
Dendrogram cuts off next of leaf entries on far right

### ISSUE THREAD

**Issue by jetpacktuxedo** [christabor/flask_jsondash#54]
![screenshot_2016-10-21_10-14-39](https://cloud.githubusercontent.com/assets/3813932/19606483/719ab330-9777-11e6-8bf5-198a0e45af51.png)

I sort of figured when I resized the chart to give it more horizontal space that it would fix it...

![screenshot_2016-10-21_10-15-24](https://cloud.githubusercontent.com/assets/3813932/19606492/83534bfa-9777-11e6-92bb-d50b04be63c4.png)

Nope. It just stretches out the lines. Maybe have a configurable option for the buffer size?

**Comment by christabor** [comment]
This is same type of issue as https://github.com/christabor/flask_jsondash/issues/55

**Comment by jetpacktuxedo** [comment]
Is it? It seems like the opposite problem to me. It is getting cut off rather than escaping the box. I figured it was probably a D3 issue, but I'm not familiar enough with js to track it down.

**Comment by christabor** [comment]
I'm thinking in general terms, like sizing of charts. But you're right in that sense. All charts do not hide any overflow, so the clipping is happening at the svg level. I will look into having some intelligent default for padding to see if that fixes the cutoff.

**Comment by christabor** [comment]
I added some padding and relative sizing, which helps in many (but not all) cases. I also added some resizing capabilities for all charts, which may significantly alleviate this problem as you can quickly resize to see how it looks.

Lemme know if that works!

**Comment by christabor** [comment]
Same situation as #55 -- fixed with some updates for auto-scaling/fitting in widget + easy to resize option.
