### ISSUE TITLE
Radial Dendrogram draws outside of chart area

### ISSUE THREAD

**Issue by jetpacktuxedo** [christabor/flask_jsondash#55]
![screenshot_2016-10-21_10-18-53](https://cloud.githubusercontent.com/assets/3813932/19606531/c75abbd0-9777-11e6-8be0-4f9f6bdad99e.png)

**Comment by christabor** [comment]
So, what would you imagine this would do to compensate? I want to try and avoid "guessing" on the layout for the user, and instead have them resize it as appropriate. Would making a resize feature that is easier be sufficient for this?

**Comment by jetpacktuxedo** [comment]
I guess I would normally expect it to scale the diagram? I tried a bunch of different sizes and it seems to automatically scale the diagram to fit within the width of the specified area, but doesn't do any sort of scaling to compensate for the height.

**Comment by christabor** [comment]
Ok, I'll see what I can whip up and we can test out something.

**Comment by christabor** [comment]
Forgot to address this, but I added some changes a while back to fix this. There is a threshold where the auto-resizing starts to break down (around 200x200 for similar complexity as the above example), but it will auto resize and maintain the ratio for most all sizes. This, combined with the fact you can now resize charts by dragging the bottom corner, should resolve this issue.

**Comment by christabor** [comment]
A more robust and I think complete, fix, exists in 58552db
