### ISSUE TITLE
Silent failure when chart size not defined

### ISSUE THREAD

**Issue by jetpacktuxedo** [christabor/flask_jsondash#57]
It at least happens with dendrogram and radial dendrogram, probably others as well.

Maybe a default value? Or make the dimension fields required?

**Comment by christabor** [comment]
The fields now have a more prominent "required" text field on each label. I will also make it default to height if only width is specified, and vice versa.

**Comment by christabor** [comment]
Scratch that. I'd rather just make it required or not. Closing since the fields are now updated.
