### ISSUE TITLE
quickstart instructions don't work -- cant load db_adapters

### ISSUE THREAD

**Issue by dlaflamme** [christabor/flask_jsondash#68]
`
➜  ~  cd flask_jsondash/
`

Create virtualenv:
`
➜  flask_jsondash git:(master) virtualenv env
Using base prefix '/usr'
New python executable in env/bin/python3
Also creating executable in env/bin/python
Installing setuptools, pip, wheel...done.
`

Activate:
➜  flask_jsondash git:(master) source env/bin/activate
(env)➜	flask_jsondash git:(master) which python
/home/Dan/flask_jsondash/env/bin/python
(env)➜	flask_jsondash git:(master) pythonnsetup.py install
running install
running bdist_egg
running egg_info
creating flask_jsondash.egg-info
writing dependency_links to flask_jsondash.egg-info/dependency_links.txt
writing top-level names to flask_jsondash.egg-info/top_level.txt
writing flask_jsondash.egg-info/PKG-INFO
writing requirements to flask_jsondash.egg-info/requires.txt
writing manifest file 'flask_jsondash.egg-info/SOURCES.txt'
reading manifest file 'flask_jsondash.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'flask_jsondash.egg-info/SOURCES.txt'
installing library code to build/bdist.cygwin-2.6.0-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/flask_jsondash
copying flask_jsondash/charts_builder.py -> build/lib/flask_jsondash
copying flask_jsondash/db_adapters.py -> build/lib/flask_jsondash
copying flask_jsondash/model_factories.py -> build/lib/flask_jsondash
copying flask_jsondash/settings.py -> build/lib/flask_jsondash
copying flask_jsondash/__init__.py -> build/lib/flask_jsondash
creating build/lib/flask_jsondash/static
copying flask_jsondash/static/__init__.py -> build/lib/flask_jsondash/static
creating build/lib/flask_jsondash/static/css
copying flask_jsondash/static/css/app.css -> build/lib/flask_jsondash/static/css
copying flask_jsondash/static/css/overrides.css -> build/lib/flask_jsondash/static/css
creating build/lib/flask_jsondash/static/css/fonts
copying flask_jsondash/static/css/fonts/fontawesome-webfont.eot -> build/lib/flask_jsondash/static/css/fonts
copying flask_jsondash/static/css/fonts/fontawesome-webfont.svg -> build/lib/flask_jsondash/static/css/fonts
copying flask_jsondash/static/css/fonts/fontawesome-webfont.ttf -> build/lib/flask_jsondash/static/css/fonts
copying flask_jsondash/static/css/fonts/fontawesome-webfont.woff -> build/lib/flask_jsondash/static/css/fonts
copying flask_jsondash/static/css/fonts/fontawesome-webfont.woff2 -> build/lib/flask_jsondash/static/css/fonts
creating build/lib/flask_jsondash/static/css/vendor
copying flask_jsondash/static/css/vendor/font-awesome.css -> build/lib/flask_jsondash/static/css/vendor
copying flask_jsondash/static/css/vendor/jquery-ui.min.css -> build/lib/flask_jsondash/static/css/vendor
copying flask_jsondash/static/css/vendor/timeline.css -> build/lib/flask_jsondash/static/css/vendor
creating build/lib/flask_jsondash/static/css/vendor/images
copying flask_jsondash/static/css/vendor/images/ui-icons_444444_256x240.png -> build/lib/flask_jsondash/static/css/vendor/images
copying flask_jsondash/static/css/vendor/images/ui-icons_555555_256x240.png -> build/lib/flask_jsondash/static/css/vendor/images
copying flask_jsondash/static/css/vendor/images/ui-icons_777620_256x240.png -> build/lib/flask_jsondash/static/css/vendor/images
copying flask_jsondash/static/css/vendor/images/ui-icons_777777_256x240.png -> build/lib/flask_jsondash/static/css/vendor/images
copying flask_jsondash/static/css/vendor/images/ui-icons_cc0000_256x240.png -> build/lib/flask_jsondash/static/css/vendor/images
copying flask_jsondash/static/css/vendor/images/ui-icons_ffffff_256x240.png -> build/lib/flask_jsondash/static/css/vendor/images
creating build/lib/flask_jsondash/static/js
copying flask_jsondash/static/js/app.js -> build/lib/flask_jsondash/static/js
copying flask_jsondash/static/js/handlers.js -> build/lib/flask_jsondash/static/js
copying flask_jsondash/static/js/utils.js -> build/lib/flask_jsondash/static/js
creating build/lib/flask_jsondash/static/js/vendor
copying flask_jsondash/static/js/vendor/jRespond.min.js -> build/lib/flask_jsondash/static/js/vendor
copying flask_jsondash/static/js/vendor/jquery-ui.min.js -> build/lib/flask_jsondash/static/js/vendor
copying flask_jsondash/static/js/vendor/masonry.pkgd.min.js -> build/lib/flask_jsondash/static/js/vendor
creating build/lib/flask_jsondash/templates
copying flask_jsondash/templates/__init__.py -> build/lib/flask_jsondash/templates
creating build/lib/flask_jsondash/templates/layouts
copying flask_jsondash/templates/layouts/charts_base.html -> build/lib/flask_jsondash/templates/layouts
creating build/lib/flask_jsondash/templates/pages
copying flask_jsondash/templates/pages/chart_detail.html -> build/lib/flask_jsondash/templates/pages
copying flask_jsondash/templates/pages/charts_index.html -> build/lib/flask_jsondash/templates/pages
creating build/lib/flask_jsondash/templates/partials
copying flask_jsondash/templates/partials/dashboard-options.html -> build/lib/flask_jsondash/templates/partials
copying flask_jsondash/templates/partials/edit-data-modal.html -> build/lib/flask_jsondash/templates/partials
copying flask_jsondash/templates/partials/form-diagram-options.html -> build/lib/flask_jsondash/templates/partials
copying flask_jsondash/templates/partials/form-json.html -> build/lib/flask_jsondash/templates/partials
copying flask_jsondash/templates/partials/form-view.html -> build/lib/flask_jsondash/templates/partials
creating build/bdist.cygwin-2.6.0-x86_64
creating build/bdist.cygwin-2.6.0-x86_64/egg
creating build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash
copying build/lib/flask_jsondash/charts_builder.py -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash
copying build/lib/flask_jsondash/db_adapters.py -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash
copying build/lib/flask_jsondash/model_factories.py -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash
copying build/lib/flask_jsondash/settings.py -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash
creating build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static
creating build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css
copying build/lib/flask_jsondash/static/css/app.css -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css
creating build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/fonts
copying build/lib/flask_jsondash/static/css/fonts/fontawesome-webfont.eot -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/fonts
copying build/lib/flask_jsondash/static/css/fonts/fontawesome-webfont.svg -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/fonts
copying build/lib/flask_jsondash/static/css/fonts/fontawesome-webfont.ttf -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/fonts
copying build/lib/flask_jsondash/static/css/fonts/fontawesome-webfont.woff -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/fonts
copying build/lib/flask_jsondash/static/css/fonts/fontawesome-webfont.woff2 -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/fonts
copying build/lib/flask_jsondash/static/css/overrides.css -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css
creating build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/vendor
copying build/lib/flask_jsondash/static/css/vendor/font-awesome.css -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/vendor
creating build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/vendor/images
copying build/lib/flask_jsondash/static/css/vendor/images/ui-icons_444444_256x240.png -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/vendor/images
copying build/lib/flask_jsondash/static/css/vendor/images/ui-icons_555555_256x240.png -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/vendor/images
copying build/lib/flask_jsondash/static/css/vendor/images/ui-icons_777620_256x240.png -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/vendor/images
copying build/lib/flask_jsondash/static/css/vendor/images/ui-icons_777777_256x240.png -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/vendor/images
copying build/lib/flask_jsondash/static/css/vendor/images/ui-icons_cc0000_256x240.png -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/vendor/images
copying build/lib/flask_jsondash/static/css/vendor/images/ui-icons_ffffff_256x240.png -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/vendor/images
copying build/lib/flask_jsondash/static/css/vendor/jquery-ui.min.css -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/vendor
copying build/lib/flask_jsondash/static/css/vendor/timeline.css -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/css/vendor
creating build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/js
copying build/lib/flask_jsondash/static/js/app.js -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/js
copying build/lib/flask_jsondash/static/js/handlers.js -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/js
copying build/lib/flask_jsondash/static/js/utils.js -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/js
creating build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/js/vendor
copying build/lib/flask_jsondash/static/js/vendor/jquery-ui.min.js -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/js/vendor
copying build/lib/flask_jsondash/static/js/vendor/jRespond.min.js -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/js/vendor
copying build/lib/flask_jsondash/static/js/vendor/masonry.pkgd.min.js -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/js/vendor
copying build/lib/flask_jsondash/static/__init__.py -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static
creating build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates
creating build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates/layouts
copying build/lib/flask_jsondash/templates/layouts/charts_base.html -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates/layouts
creating build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates/pages
copying build/lib/flask_jsondash/templates/pages/charts_index.html -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates/pages
copying build/lib/flask_jsondash/templates/pages/chart_detail.html -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates/pages
creating build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates/partials
copying build/lib/flask_jsondash/templates/partials/dashboard-options.html -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates/partials
copying build/lib/flask_jsondash/templates/partials/edit-data-modal.html -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates/partials
copying build/lib/flask_jsondash/templates/partials/form-diagram-options.html -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates/partials
copying build/lib/flask_jsondash/templates/partials/form-json.html -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates/partials
copying build/lib/flask_jsondash/templates/partials/form-view.html -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates/partials
copying build/lib/flask_jsondash/templates/__init__.py -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates
copying build/lib/flask_jsondash/__init__.py -> build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash
byte-compiling build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/charts_builder.py to charts_builder.cpython-34.pyc
byte-compiling build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/db_adapters.py to db_adapters.cpython-34.pyc
byte-compiling build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/model_factories.py to model_factories.cpython-34.pyc
byte-compiling build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/settings.py to settings.cpython-34.pyc
byte-compiling build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/static/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/templates/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.cygwin-2.6.0-x86_64/egg/flask_jsondash/__init__.py to __init__.cpython-34.pyc
creating build/bdist.cygwin-2.6.0-x86_64/egg/EGG-INFO
copying flask_jsondash.egg-info/PKG-INFO -> build/bdist.cygwin-2.6.0-x86_64/egg/EGG-INFO
copying flask_jsondash.egg-info/SOURCES.txt -> build/bdist.cygwin-2.6.0-x86_64/egg/EGG-INFO
copying flask_jsondash.egg-info/dependency_links.txt -> build/bdist.cygwin-2.6.0-x86_64/egg/EGG-INFO
copying flask_jsondash.egg-info/not-zip-safe -> build/bdist.cygwin-2.6.0-x86_64/egg/EGG-INFO
copying flask_jsondash.egg-info/requires.txt -> build/bdist.cygwin-2.6.0-x86_64/egg/EGG-INFO
copying flask_jsondash.egg-info/top_level.txt -> build/bdist.cygwin-2.6.0-x86_64/egg/EGG-INFO
creating dist
creating 'dist/flask_jsondash-4.0.0-py3.4.egg' and adding 'build/bdist.cygwin-2.6.0-x86_64/egg' to it
removing 'build/bdist.cygwin-2.6.0-x86_64/egg' (and everything under it)
Processing flask_jsondash-4.0.0-py3.4.egg
creating /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/flask_jsondash-4.0.0-py3.4.egg
Extracting flask_jsondash-4.0.0-py3.4.egg to /home/Dan/flask_jsondash/env/lib/python3.4/site-packages
Adding flask-jsondash 4.0.0 to easy-install.pth file

Installed /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/flask_jsondash-4.0.0-py3.4.egg
Processing dependencies for flask-jsondash==4.0.0
Searching for WTForms==2.1
Reading https://pypi.python.org/simple/WTForms/
Best match: WTForms 2.1
Downloading https://pypi.python.org/packages/bf/91/2e553b86c55e9cf2f33265de50e052441fb753af46f5f20477fe9c61280e/WTForms-2.1.zip#md5=6938a541fafd1a1ae2f6b9b88588eef2
Processing WTForms-2.1.zip
Writing /tmp/easy_install-kuzsbaue/WTForms-2.1/setup.cfg
Running WTForms-2.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kuzsbaue/WTForms-2.1/egg-dist-tmp-xb628ila
warning: no previously-included files matching '*' found under directory 'docs/_build'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
zip_safe flag not set; analyzing archive contents...
wtforms.__pycache__.i18n.cpython-34: module references __file__
creating /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/WTForms-2.1-py3.4.egg
Extracting WTForms-2.1-py3.4.egg to /home/Dan/flask_jsondash/env/lib/python3.4/site-packages
Adding WTForms 2.1 to easy-install.pth file

Installed /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/WTForms-2.1-py3.4.egg
Searching for Werkzeug==0.11.10
Reading https://pypi.python.org/simple/Werkzeug/
Best match: Werkzeug 0.11.10
Downloading https://pypi.python.org/packages/b7/7f/44d3cfe5a12ba002b253f6985a4477edfa66da53787a2a838a40f6415263/Werkzeug-0.11.10.tar.gz#md5=780967186f9157e88f2bfbfa6f07a893
Processing Werkzeug-0.11.10.tar.gz
Writing /tmp/easy_install-zp4d29tt/Werkzeug-0.11.10/setup.cfg
Running Werkzeug-0.11.10/setup.py -q bdist_egg --dist-dir /tmp/easy_install-zp4d29tt/Werkzeug-0.11.10/egg-dist-tmp-qeiyjn9i
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/_themes'
warning: no previously-included files matching '*.py[cdo]' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.pyd' found anywhere in distribution
creating /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/Werkzeug-0.11.10-py3.4.egg
Extracting Werkzeug-0.11.10-py3.4.egg to /home/Dan/flask_jsondash/env/lib/python3.4/site-packages
Adding Werkzeug 0.11.10 to easy-install.pth file

Installed /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/Werkzeug-0.11.10-py3.4.egg
Searching for pymongo==3.3.0
Reading https://pypi.python.org/simple/pymongo/
Best match: pymongo 3.3.0
Downloading https://pypi.python.org/packages/31/63/5a7826bdee88db6d49ef1737a17de63cf6f50f8cb04f2a0339f048cb33b5/pymongo-3.3.0.tar.gz#md5=42cd12a5014fb7d3e1987ca04f5c651f
Processing pymongo-3.3.0.tar.gz
Writing /tmp/easy_install-grm8ojrq/pymongo-3.3.0/setup.cfg
Running pymongo-3.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-grm8ojrq/pymongo-3.3.0/egg-dist-tmp-8tsnndmz
zip_safe flag not set; analyzing archive contents...
bson.__pycache__._cbson.cpython-34: module references __file__
pymongo.__pycache__._cmessage.cpython-34: module references __file__
creating /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/pymongo-3.3.0-py3.4-cygwin-2.6.0-x86_64.egg
Extracting pymongo-3.3.0-py3.4-cygwin-2.6.0-x86_64.egg to /home/Dan/flask_jsondash/env/lib/python3.4/site-packages
Adding pymongo 3.3.0 to easy-install.pth file

Installed /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/pymongo-3.3.0-py3.4-cygwin-2.6.0-x86_64.egg
Searching for MarkupSafe==0.23
Reading https://pypi.python.org/simple/MarkupSafe/
Best match: MarkupSafe 0.23
Downloading https://pypi.python.org/packages/c0/41/bae1254e0396c0cc8cf1751cb7d9afc90a602353695af5952530482c963f/MarkupSafe-0.23.tar.gz#md5=f5ab3deee4c37cd6a922fb81e730da6e
Processing MarkupSafe-0.23.tar.gz
Writing /tmp/easy_install-f6kpl21f/MarkupSafe-0.23/setup.cfg
Running MarkupSafe-0.23/setup.py -q bdist_egg --dist-dir /tmp/easy_install-f6kpl21f/MarkupSafe-0.23/egg-dist-tmp-78ugcsyw
creating /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/MarkupSafe-0.23-py3.4-cygwin-2.6.0-x86_64.egg
Extracting MarkupSafe-0.23-py3.4-cygwin-2.6.0-x86_64.egg to /home/Dan/flask_jsondash/env/lib/python3.4/site-packages
Adding MarkupSafe 0.23 to easy-install.pth file

Installed /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/MarkupSafe-0.23-py3.4-cygwin-2.6.0-x86_64.egg
Searching for Jinja2==2.8
Reading https://pypi.python.org/simple/Jinja2/
Best match: Jinja2 2.8
Downloading https://pypi.python.org/packages/f2/2f/0b98b06a345a761bec91a079ccae392d282690c2d8272e708f4d10829e22/Jinja2-2.8.tar.gz#md5=edb51693fe22c53cee5403775c71a99e
Processing Jinja2-2.8.tar.gz
Writing /tmp/easy_install-lxr3r3ga/Jinja2-2.8/setup.cfg
Running Jinja2-2.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-lxr3r3ga/Jinja2-2.8/egg-dist-tmp-7h59jbx2
warning: no files found matching 'run-tests.py'
warning: no files found matching '*' under directory 'custom_fixers'
warning: no files found matching '*' under directory 'jinja2/testsuite/res'
warning: no previously-included files matching '*' found under directory 'docs/_build'
warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
creating /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/Jinja2-2.8-py3.4.egg
Extracting Jinja2-2.8-py3.4.egg to /home/Dan/flask_jsondash/env/lib/python3.4/site-packages
Adding Jinja2 2.8 to easy-install.pth file

Installed /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/Jinja2-2.8-py3.4.egg
Searching for itsdangerous==0.24
Reading https://pypi.python.org/simple/itsdangerous/
Best match: itsdangerous 0.24
Downloading https://pypi.python.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz#md5=a3d55aa79369aef5345c036a8a26307f
Processing itsdangerous-0.24.tar.gz
Writing /tmp/easy_install-kssc9a7t/itsdangerous-0.24/setup.cfg
Running itsdangerous-0.24/setup.py -q bdist_egg --dist-dir /tmp/easy_install-kssc9a7t/itsdangerous-0.24/egg-dist-tmp-m8fsj7sc
warning: no previously-included files matching '*' found under directory 'docs/_build'
creating /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/itsdangerous-0.24-py3.4.egg
Extracting itsdangerous-0.24-py3.4.egg to /home/Dan/flask_jsondash/env/lib/python3.4/site-packages
Adding itsdangerous 0.24 to easy-install.pth file

Installed /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/itsdangerous-0.24-py3.4.egg
Searching for Flask-WTF==0.12
Reading https://pypi.python.org/simple/Flask-WTF/
Best match: Flask-WTF 0.12
Downloading https://pypi.python.org/packages/f6/fe/9fe6a8a4edcc39f8ec365dc16d292d659f7a77a0ed596947f29c0c5c9dc1/Flask-WTF-0.12.tar.gz#md5=c53a74e8ba481bf53405fd5efdf0339e
Processing Flask-WTF-0.12.tar.gz
Writing /tmp/easy_install-hvc_ise6/Flask-WTF-0.12/setup.cfg
Running Flask-WTF-0.12/setup.py -q bdist_egg --dist-dir /tmp/easy_install-hvc_ise6/Flask-WTF-0.12/egg-dist-tmp-bielt_xh
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/_themes/.git'
creating /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/Flask_WTF-0.12-py3.4.egg
Extracting Flask_WTF-0.12-py3.4.egg to /home/Dan/flask_jsondash/env/lib/python3.4/site-packages
Adding Flask-WTF 0.12 to easy-install.pth file

Installed /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/Flask_WTF-0.12-py3.4.egg
Searching for Flask==0.10.1
Reading https://pypi.python.org/simple/Flask/
Best match: Flask 0.10.1
Downloading https://pypi.python.org/packages/db/9c/149ba60c47d107f85fe52564133348458f093dd5e6b57a5b60ab9ac517bb/Flask-0.10.1.tar.gz#md5=378670fe456957eb3c27ddaef60b2b24
Processing Flask-0.10.1.tar.gz
Writing /tmp/easy_install-unh2nk2k/Flask-0.10.1/setup.cfg
Running Flask-0.10.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-unh2nk2k/Flask-0.10.1/egg-dist-tmp-d085govc
warning: no files found matching '*' under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'examples'
warning: no previously-included files matching '*.pyo' found under directory 'examples'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/_themes/.git'
creating /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg
Extracting Flask-0.10.1-py3.4.egg to /home/Dan/flask_jsondash/env/lib/python3.4/site-packages
Adding Flask 0.10.1 to easy-install.pth file

Installed /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg
Searching for click==6.6
Reading https://pypi.python.org/simple/click/
Best match: click 6.6
Downloading https://pypi.python.org/packages/7a/00/c14926d8232b36b08218067bcd5853caefb4737cda3f0a47437151344792/click-6.6.tar.gz#md5=d0b09582123605220ad6977175f3e51d
Processing click-6.6.tar.gz
Writing /tmp/easy_install-az1v8yun/click-6.6/setup.cfg
Running click-6.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-az1v8yun/click-6.6/egg-dist-tmp-2w27pvzj
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyo' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'examples'
warning: no previously-included files matching '*.pyo' found under directory 'examples'
no previously-included directories found matching 'docs/_build'
zip_safe flag not set; analyzing archive contents...
click.__pycache__.core.cpython-34: module references __file__
creating /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/click-6.6-py3.4.egg
Extracting click-6.6-py3.4.egg to /home/Dan/flask_jsondash/env/lib/python3.4/site-packages
Adding click 6.6 to easy-install.pth file

Installed /home/Dan/flask_jsondash/env/lib/python3.4/site-packages/click-6.6-py3.4.egg
Finished processing dependencies for flask-jsondash==4.0.0
`

Try running:
`
(env)➜	flask_jsondash git:(master) python app.py
python: can't open file 'app.py': [Errno 2] No such file or directory
`
Try running from example app:
`
(env)➜	flask_jsondash git:(master) cd example_app/
(env)➜	example_app git:(master) python app.py
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from flask_jsondash.charts_builder import charts
  File "/home/Dan/flask_jsondash/env/lib/python3.4/site-packages/flask_jsondash-4.0.0-py3.4.egg/flask_jsondash/charts_builder.py", line 30, in <module>
    import db_adapters as adapter
ImportError: No module named 'db_adapters'
(env)➜	example_app git:(master)
%
(env)➜	example_app git:(master)
`
Path:
`
(env)➜	example_app git:(master) python -c 'import sys; print('\n".join(sys.path"\n".join(sys.path))'

/home/Dan/flask_jsondash/env/lib/python3.4/site-packages/flask_jsondash-4.0.0-py3.4.egg
/home/Dan/flask_jsondash/env/lib/python3.4/site-packages/WTForms-2.1-py3.4.egg
/home/Dan/flask_jsondash/env/lib/python3.4/site-packages/Werkzeug-0.11.10-py3.4.egg
/home/Dan/flask_jsondash/env/lib/python3.4/site-packages/pymongo-3.3.0-py3.4-cygwin-2.6.0-x86_64.egg
/home/Dan/flask_jsondash/env/lib/python3.4/site-packages/MarkupSafe-0.23-py3.4-cygwin-2.6.0-x86_64.egg
/home/Dan/flask_jsondash/env/lib/python3.4/site-packages/Jinja2-2.8-py3.4.egg
/home/Dan/flask_jsondash/env/lib/python3.4/site-packages/itsdangerous-0.24-py3.4.egg
/home/Dan/flask_jsondash/env/lib/python3.4/site-packages/Flask_WTF-0.12-py3.4.egg
/home/Dan/flask_jsondash/env/lib/python3.4/site-packages/Flask-0.10.1-py3.4.egg
/home/Dan/flask_jsondash/env/lib/python3.4/site-packages/click-6.6-py3.4.egg
/home/Dan/flask_jsondash/env/lib/python34.zip
/home/Dan/flask_jsondash/env/lib/python3.4
/home/Dan/flask_jsondash/env/lib/python3.4/plat-cygwin
/home/Dan/flask_jsondash/env/lib/python3.4/lib-dynload
/usr/lib/python3.4
/usr/lib/python3.4/plat-cygwin
/home/Dan/flask_jsondash/env/lib/python3.4/site-packages
(env)➜	example_app git:(master) deactivate
➜  example_app git:(master)
`

**Comment by christabor** [comment]
I'll take a look "tomorrow" (today)!

**Comment by christabor** [comment]
Btw, I notice that you are using python3.4 here in your virtualenv. I have not tested this on python 3 as of yet. Have you tried 2.7 yet?

**Comment by dlaflamme** [comment]
Yes, you are correct. Forcing python2.7 (specifically, by doing "virtualenv --python=python2.7 env") does make it work.

I don't know enough about the differences between python 2 and 3 to understand why it doesn't work in python 3, but if you have suggestions that that you'd like me to test, I'd be happy to.

**Comment by christabor** [comment]
I will see what it takes to make it work in both versions. For now though, I think your best bet is 2.7. I'm thinking it's isolated to the way imports work, but we'll see.

**Comment by christabor** [comment]
@dlaflamme I believe I have found the culprit and fixed it. I tested it on 2.7 and 3.4 and it runs fine on both.
