### ISSUE TITLE
trouble getting started

### ISSUE THREAD

**Issue by oksigma** [christabor/flask_jsondash#79]
When start the app (ie python run.py) there arent any plots that appear on the page, only a link to /charts/.  I cant even get it started?  Surely i am missing something very simple in the configuration ? 

I have uploaded a screenshot of what I am getting.

<img width="623" alt="screen shot 2016-12-14 at 5 56 49 pm" src="https://cloud.githubusercontent.com/assets/19620383/21172565/bf4c3b74-c226-11e6-8032-4509502e7ef5.png">

when enter url /charts/plotly

<img width="618" alt="screen shot 2016-12-14 at 5 55 08 pm" src="https://cloud.githubusercontent.com/assets/19620383/21172527/9275935c-c226-11e6-81d3-1049cfd5dd01.png">

**Comment by christabor** [comment]
No database is populated when you run the app. You'll need to add a new record in mongo (assuming you have mongo installed and running, see https://github.com/christabor/flask_jsondash#mongodb for more on that).

To do that:

1. Create a new dashboard, call it whatever you want.
2. Copy over an example json config from https://github.com/christabor/flask_jsondash/tree/master/example_app/examples/config and choose "edit > edit raw config" from the edit button near the dashboard title to open up the raw config textbox.
3. Paste in the config json and save.

**Comment by christabor** [comment]
@oksigma Did that help?

**Comment by Pengman** [comment]
I have the same problem.
How do I "Create a new dashboard, call it whatever you want." ?

**Comment by oksigma** [comment]
thankyou it did help.  I re-installed it and it worked pretty much straight away, so I think I may had a version issue, perhaps it was because I originally downloaded it using pip.

**Comment by christabor** [comment]
@Pengman regarding step 1: 

1a. From the homepage, click "create new dashboard". 
1b. Where it says "View Name", in the text input, fill out whatever title you want for your dashboard.
1c. Click the blue "save" button to the right.

This should take you to your new chart, where you can paste in a raw json config.

**Comment by christabor** [comment]
@oksigma I pushed a new release into pypi, so this should work as-is with a `pip install` as well. Closing if there are no more issues.

**Comment by Pengman** [comment]
@christabor Yeah, I had the same issue where a nonstandard setup (not following the guide) caused that part of the site to be missing. It worked when I followed the guide.

**Comment by christabor** [comment]
Glad to hear!
